sub-scale=1.8
window-maximized=yes
autocreate-playlist=same
keep-open=always
alang=jpn,ja,eng,en
save-position-on-quit=yes

# Automatically select secondary subtitles if matching languages are found
secondary-sid=auto
sub-ass-override=force
